---
title: "Teori Peluang"
subtitle: "Pekan 2 – Kaidah Kombinatorial"
author:
  - name: Indira Puteri Kinasih
    orcid: 0009-0009-6959-6723
    email: indiraputeri@uinmataram.ac.id
    affiliations: Universitas Islam Negeri Mataram
format:
  ubd-revealjs:
    output-file: index.html
    self-contained: true
    chalkboard: false
    toc: false
    toc-depth: 1
    transition: fade
    auto-stretch: false
    width: 1250  # 1050
    height: 760  # 700
execute:
  echo: false
---

## Tujuan Pembelajaran Pekan 2

Setelah perkuliahan ini, mahasiswa diharapkan mampu:

- Memahami mengapa teknik menghitung penting dalam peluang

- Menggunakan aturan perkalian (*basic counting principle*)

- Membedakan dan menerapkan:

   - Permutasi
   - Kombinasi

- Menyelesaikan soal peluang sederhana berbasis *counting*

## "*Mengapa kombinatorial penting?*"

Sebuah sistem komunikasi terdiri dari $n$ antena yang disusun berjajar.

- Sebagian antena bisa rusak (0), sisanya berfungsi (1)
- Sistem disebut berfungsi jika tidak ada dua antena rusak yang bersebelahan
- contoh: $n = 4$ and $m = 2$, dimana $m$ adalah banyaknya antena yang rusak
- berarti ada 6 konfigurasi/susunan yang mungkin:

$$
\begin{matrix}
0 & 1 & 1 & 0 \\
0 & 1 & 0 & 1 \\
1 & 0 & 1 & 0 \\
0 & 0 & 1 & 1 \\
1 & 0 & 0 & 1 \\
1 & 1 & 0 & 0
\end{matrix}
$$

## Aturan perkalian

::: {.callout-note}
### Aturan Perkalian

Misalkan dua percobaan dilakukan. Jika eksperimen 1 dapat menghasilkan $m$ hasil yang mungkin, dan jika untuk setiap hasil di eksperimen 1, ada $n$ hasil yang mungkin pada eksperimen 2, maka, secara keseluruhan ada $mn$ hasil yang mungkin dari keduanya
:::



$$
\begin{array}{lll}
(1,1), & (1,2), & \ldots,\ (1,n) \\
(2,1), & (2,2), & \ldots,\ (2,n) \\
\vdots & \vdots & \vdots \\
(m,1), & (m,2), & \ldots,\ (m,n)
\end{array}
$$

## Contoh 1a

Suatu program studi memiliki 5 kelas, dan setiap kelas terdiri dari 30 mahasiswa. Jika akan dipilih satu kelas dan satu mahasiswa dari kelas tersebut, berapa banyak kemungkinan pilihan?

**Solusi**


## Secara umum...

::: {.callout-note}
### Aturan perkalian yang diperumum

Misalkan ada $r$ percobaan sedemikian sehingga percobaan pertama menghsilkan $n_1$ kemungkinan hasil; dan jika untuk setiap hasil tersebut, ada $n_2$ hasil yang mungkin pada percobaan kedua; dan jika untuk setiap hasil yang mungkin pada dua percobaan pertama, ada $n_3$ hasil yang mungkin pada percobaan ketiga; dan seterusnya..., maka terdapat total $n_1\ .\ n_2\ \dots\ n_r$ hasil yang mungkin dari $r$ percobaan tersebut
:::

## Contoh 1b

Suatu sekolah memiliki 2 guru Matematika, 3 guru IPA, 4 guru Bahasa, dan 2 guru IPS. Akan dipilih tim kecil yang terdiri dari satu guru dari setiap bidang.

**Solusi:**


## Contoh 1c

Ada berapa plat nomor kendaraan yang mungkin disusun jika 2 digit pertama berisi huruf dan 4 digit berikutnya berisi angka?

**Solusi**


## Permutasi: Urutan itu penting

> *Berapa banyak susunan yang mungkin dari huruf $a$, $b$, dan $c$?*

- semua kemungkinan susunannya adalah: 

$$
abc,acb,bac,bca,cba
$$

- Total ada 6 susunan berbeda

- Setiap susunan berurutan seperti ini disebut **permutasi**.

## Permutasi: kaitannya dengan aturan perkalian

Untuk menyusun 3 huruf:

- Posisi pertama: 3 pilihan

- Posisi kedua: 2 pilihan tersisa

- Posisi ketiga: 1 pilihan tersisa

Dengan prinsip dasar penghitungan: $3 \times 2 \times 1 = 6$

::: {.callout-important}
### Permutasi

$$
n! = n\ . (n-1)\ . (n-2)\ \dots\ 3\ . 2\ .1
$$

:::

::: aside
note: notasi $!$ dibaca *faktorial* 
:::


## Contoh 1d

Misalkan kelas teori peluang terdiri dari 7 mahasiswa dan 5 mahasiswi. Mereka diberikan suatu ujian, dan mereka akan dirangking berdasarkan hasil ujian tersebut. Asumsinya, tidak ada 2 mahasiswa/i yang memiliki nilai sama.

 - berapa komposisi ranking berbeda yang mungkin?
 - Jika mahasiswa dirangking hanya diantara sesama mereka, begitu juga mahasiswi, berapa susunan rangking yang mungkin?

*Solusi:*

## Permutasi dengan objek yang sama

> *Berapa banyak susunan huruf berbeda dari kata "STATISTIKA"?*

- kata "STATISTIKA" terdiri dari 10 huruf;

- jika setiap huruf dianggap berbeda, dan sesuai dengan kaidah permutasi, maka banyaknya susunan yang berbeda adalah $10! = \dots$

- tapi, apakah itu sudah benar?

$$
S_1\ T_1\ A_1\ T_2\ I_1\ S_2\ T_3\ I_2\ K\ A_2
$$

- tentu BELUM BENAR! karena
   
   - menukar $S_1$ dengan $S_2$ akan menghasilkan susunan yg sama saja
   - demikian juga huruf kembar lainnya

## (cont'd)

$$
S_1\ T_1\ A_1\ T_2\ I_1\ S_2\ T_3\ I_2\ K\ A_2
$$

- huruf $S$ dapat dipertukarkan sebanyak $2!$ cara
- huruf $T$ dapat dipertukarkan sebanyak $3!$ cara
- huruf $A$ dapat dipertukarkan sebanyak $2!$ cara
- huruf $I$ dapat dipertukarkan sebanyak $2!$ cara

:::{.callout style="background-color:#eeeeee;"}

Karena pertukaran huruf yg sama tidak akan menghasilkan susunan baru, 
maka kita harus membagi $\frac{10!}{2!\ . 3!\ . 2!\ . 2!\ } = \dots$

:::

## Kombinasi: urutan tidaklah penting

- Kita sering ingin mengetahui berapa banyak kelompok berukuran $r$ 
yang dapat dibentuk dari $n$ objek.

- Contoh: "*Berapa banyak cara memilih 2 objek dari 4 objek:
A, B, C, D?*"

- jika memakai kaidah permutasi, maka $\dots$
- jika memakai kombinasi $\dots$

## Kombinasi (contd')

::: callout-note
# Notasi & Terminologi

untuk $r \le n$, $\binom{n}{r}$ didefinisikan sebagai

$$
\binom{n}{r} = \frac{n!}{(n-r)! \, r!}
$${#eq-comb}

$\binom{n}{r}$ menyatakan banyaknya
kombinasi dari $n$ objek yang diambil $r$ sekaligus.

:::

Jadi, $\binom{n}{r}$ menyatakan jumlah cara memilih 
$r$ objek dari $n$ objek [**tanpa memperhatikan urutan**]{.ubdred}.

## Contoh 1f

dari 12 mahasiswa, akan dipilih 5 orang untuk menjadi pengurus himpunan. Berapa banyak komposisi tim yang mungkin dibentuk?

*solusi*

## Identitas kombinatorik

$$
\binom{n}{r} = \binom{n-1}{r-1}+\binom{n-1}{r}, \ 1\leq r \le n
$$ {#eq-idtcomb}

- Misalkan ada $n$ orang, dan kita ingin memilih $r$ orang untuk membentuk tim.
- Fokus pada satu orang tertentu (misal: [**Dika**]{.ubdblue}).
- Setiap tim ukuran $r$ pasti termasuk salah satu dari dua jenis:

    1. Tim yang ada [**Dika**]{.ubdblue}-nya $\longrightarrow$ $\binom{n-1}{r-1}$
       
    2. Tim yang tidak ada [**Dika**]{.ubdblue}-nya $\longrightarrow$ $\binom{n-1}{r}$
- Karena semua komposisi tim pasti terdiri dari komposisi (1) + (2), maka dapat ditulis seperti pada @eq-idtcomb

## Teorema Binomial

nilai $\binom{n}{r}$ disebut juga sebagai koefisien binomial

$$
(x+y)^n = \sum_{k=0}^n\binom{n}{k}x^ky^{n-k}
$${#eq-binom}

## 